version: "3.3"
services:
  war:
    build:
      context: .
    container_name: usik-backend
    ports:
      - 8080:8080
  db:
    build: sql/
    container_name: usik-database
    ports:
      - 8081:8081
    command: java -cp ./lib/h2-1.4.200.jar org.h2.tools.RunScript -url jdbc:h2:mem:training -script insert.sql
