CREATE SCHEMA IF NOT EXISTS TRAINING;
SET SCHEMA TRAINING;

CREATE TABLE IF NOT EXISTS TRAINING.USER
(
    id         NUMBER  NOT NULL PRIMARY KEY AUTO_INCREMENT,
    login      varchar NOT NULL,
    password   varchar NOT NULL,
    email      varchar NOT NULL UNIQUE,
    first_name varchar NOT NULL,
    last_name  varchar NOT NULL,
    birthday   DATE    NOT NULL,
    role_id    NUMBER  NOT NULL
);

CREATE TABLE IF NOT EXISTS TRAINING.ROLE
(
    id   NUMBER  NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR NOT NULL
);

ALTER TABLE IF EXISTS TRAINING.USER
    ADD CONSTRAINT IF NOT EXISTS FKUser FOREIGN KEY (role_id) REFERENCES TRAINING.ROLE (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE;
